version: '3'

services:
  redis:
    image: 'redis:latest'
    command: redis-server
    volumes:
      - 'redis:/var/lib/redis/data'
  elasticsearch:
    image: elasticsearch:6.4.1
    volumes:
      - esdata:/usr/share/elasticsearch/data
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: 'rise_rp'
      POSTGRES_PASSWORD: 'rise_rp_password'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  web:
    tty: true
    stdin_open: true
    links:
      - 'postgres'
      - 'elasticsearch'
    depends_on:
      - 'postgres'
      - 'elasticsearch'
    build: .
    ports:
      - '4000:4000'
    volumes:
      - '.:/rise_rp'
    env_file:
      - '.env'
volumes:
  postgres:
  esdata:
  redis:

