version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: 'rise_rp'
      POSTGRES_PASSWORD: 'rise_rp_password'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  web:
    tty: true
    stdin_open: true
    links:
      - 'postgres'
    build: .
    ports:
      - '4000:4000'
    volumes:
      - '.:/rise_rp'
    env_file:
      - '.env'

  elasticsearch:
    build: ./docker_containers/elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  postgres:
  esdata:

